### ISSUE TITLE
DDSpacePointBuilder fails to construct 3D space points from SET strips

### ISSUE THREAD

**Issue by dudarboh** [iLCSoft/MarlinTrkProcessors#50]
- Relevant in iLCSoft `v02-02-02`

# Description

A lot of tracks in the barrel are missing reconstructed SET 3D space point (TrackerHit). Majorly missing in regions closer to the edges between SET sensors, despite available proper SimHits in the SET.
See plots below:
1. Number of SET hits associated with the track in the barrel (~ 25 % missing SET hit)
2. Number of SET hits vs Z coordinate of track position in the SET. (smeared for better visualization)
3. Distribution of All SimHits and only those matched to the reconstructed point. Reconstruction efficiency drops periodically between sensors

<img src="https://user-images.githubusercontent.com/28848011/129721443-525df337-0037-4721-b7f1-088512f05d8d.png" alt="n_set_hits" width="400"/>

<img src="https://user-images.githubusercontent.com/28848011/129721456-a6fe27ce-18a9-452e-8119-e80db7b258cc.png" alt="set_hits_z" width="400"/>

<img src="https://user-images.githubusercontent.com/28848011/129722872-fdfa7254-0e92-4077-923b-35e047533e87.png" alt="set_hits_z" width="400"/>

# Expected behavior

The majority of two SET strips construct a proper 3D space point independently of distance to the sensor edge.

**Comment by dudarboh** [comment]
Might be caused by:
https://github.com/iLCSoft/MarlinTrk/blob/d0f2367899eda66a15476fdd9ac291ba5a1c2985/src/MarlinTrkUtils.cc#L449-L516

3D space points are not written in the track ( even if 3D Space Point constructed correctly ) if both strips are outliers in the fit.

Are 25% of SET hits being rejected by the fitter? chi2 cut? etc...

**Comment by gaede** [comment]
If I understand your second plot correctly, the missing space points are already in the collection created by the space point builder - so it cannot be due to outlier removal during tracking, right ?

**Comment by dudarboh** [comment]
Yes, you are right.
I forgot that I had looked into collection of SET hits itself

**Comment by dudarboh** [comment]
Hits are discarded, because found intersection exceeds of length of one of the strips.
So the `m` or `n` parameter of the intersection point don't fit in the [-1, 1] range as they should.

See example below which represent the most of the cases:
Intersection on a green line is out of red strip range.
<img src="https://user-images.githubusercontent.com/28848011/135087894-9a6e9667-c7ed-4e04-8397-9e5ef4db92aa.png" alt="drawing" width="600"/>

However, position of the strips taken to construct the Spacepoint is weird, as the mid points are not in the middle of the sensors and strips cross sensor boundaries...


I think the problem is:

[Here](https://github.com/iLCSoft/MarlinTrkProcessors/blob/0c06ad16983b6cba545d561c5d8a5b43bcebce6d/source/Digitisers/src/DDSpacePointBuilder.cc#L514-L517) SpacePointBuilder uses strip position (`TrackerHitPlane::getPosition()`) assuming this is the midpoint of the strip. Relevant pseudo-code:

```
// TrackerHitPlane a;
const double* pa = a->getPosition();
double xa = pa[0];
double ya = pa[1];
double za = pa[2];
CLHEP::Hep3Vector PA( xa,ya,za );
dd4hep::rec::Vector3D ddPA( xa * dd4hep::mm, ya * dd4hep::mm, za * dd4hep::mm );
dd4hep::rec::Vector2D L1 = msA->globalToLocal(ddPA);

// supposed to be end points of the strip. 
dd4hep::rec::Vector2D ddSL1( L1.u(),(-stripLength * dd4hep::mm)/2.0 );
dd4hep::rec::Vector2D ddEL1( L1.u(),(stripLength * dd4hep::mm)/2.0 );
```
`+- stripLength` in the V coordinate requires `L1` and thus `a->getPosition()` to be the middle of the strip.


However the `DDPlanarDigiProcessor` writes in the strip hit middle position smeared with a Gaussian [here](https://github.com/iLCSoft/MarlinTrkProcessors/blob/0c06ad16983b6cba545d561c5d8a5b43bcebce6d/source/Digitisers/src/DDPlanarDigiProcessor.cc#L476)!

Relevant code:
```
        double uSmear  = gsl_ran_gaussian( _rng, resU ) ;
        dd4hep::rec::Vector3D newPosTmp = 1./dd4hep::mm  * ( ! _isStrip  ? 
                                                            surf->localToGlobal( dd4hep::rec::Vector2D (  ( uL + uSmear ) * dd4hep::mm, ( vL + vSmear )  *dd4hep::mm ) )  :
                                                            surf->localToGlobal( dd4hep::rec::Vector2D (  ( uL + uSmear ) * dd4hep::mm,          0.                  ) ) 
                                                            ) ;
          newPos     = newPosTmp ;
      trkHit->setPosition( newPos.const_array()  ) ;

```
from the Standard reco: resU = 0.007

I don't think SpacePointBuilder can account for this in any way...

Wouldn't it be better to store mid point without smearing as the position of the Strip hit.

TODO:
[x] Check this hypothesis by rerunning DDPlanarDigiProcessor and SpacePointBuilder without smearing.
[x] Check if removing this smearing affects anyhow SIT, FTD?

**Comment by dudarboh** [comment]
The surface coordinate system in this example looks like this:


![uv1](https://user-images.githubusercontent.com/28848011/135116092-b134f443-b194-4548-9830-b6ba2b78536e.png)

 - `u` is perpendicular to the strip
 - `V` is parallel to the strip
 - `origin` is the center of the sensor

In the digitizer , we set `V` coordinate for strip hits to `0` here:

https://github.com/iLCSoft/MarlinTrkProcessors/blob/0c06ad16983b6cba545d561c5d8a5b43bcebce6d/source/Digitisers/src/DDPlanarDigiProcessor.cc#L420-L423

which makes it more far away from the middle line of the sensor, the closer hits to the edge with the next modules..

One should set `V` such, that the strips are always in the middle.

I am not sure, if this is a special "SET" bug or it also affects FTD and SIT?

@gaede , @tmadlener 


















However the `DDPlanarDigiProcessor` writes in the strip hit middle position smeared with a Gaussian [here](https://github.com/iLCSoft/MarlinTrkProcessors/blob/0c06ad16983b6cba545d561c5d8a5b43bcebce6d/source/Digitisers/src/DDPlanarDigiProcessor.cc#L476)!

Relevant code:
```
        double uSmear  = gsl_ran_gaussian( _rng, resU ) ;
        dd4hep::rec::Vector3D newPosTmp = 1./dd4hep::mm  * ( ! _isStrip  ? 
                                                            surf->localToGlobal( dd4hep::rec::Vector2D (  ( uL + uSmear ) * dd4hep::mm, ( vL + vSmear )  *dd4hep::mm ) )  :
                                                            surf->localToGlobal( dd4hep::rec::Vector2D (  ( uL + uSmear ) * dd4hep::mm,          0.                  ) ) 
                                                            ) ;
          newPos     = newPosTmp ;
      trkHit->setPosition( newPos.const_array()  ) ;

```

**Comment by dudarboh** [comment]
This most probably also affects FTD strip disks:

<img src="https://user-images.githubusercontent.com/28848011/137934585-37252173-c8dc-471b-b95e-d71233de8f9e.png" alt="n_set_hits" width="400"/><img src="https://user-images.githubusercontent.com/28848011/137934649-c5b60e3f-57b5-4808-93c2-1417c7191fb0.png" alt="n_set_hits" width="400"/>

 - From stat boxes one can estimate total efficiency of compositing space points for FTD which is ~ 82.7 %

I wanted to check the position of digitized strips in the event display, but it is not so trivial to show for the FTD that the position is biased if it is...

Just to show some example case for the thought:
![Screenshot from 2021-10-19 18-56-23](https://user-images.githubusercontent.com/28848011/137956968-5d3ab746-ffa6-4b2b-bc08-ae411103c809.png)

Strips radially exceed the boundaries is expected behaviour...
Ideally all disks should have different strip length, but as it is currently implemented, we assume equal strip lengths for all disks for simplicity and reject space points if they are reconstructed outside of surface boundaries

However, one needs to pay attention to the middle position of the strips...
I assume we expect them to be radially on the middle of the sensors.
However if they as well as SET strips are digitized to be with `V = 0` coordinate, then they also deviate from the middle sensor position as `V` is perpendicular to the strips which are tilted by the 5 degrees..

I will try to put them on the middle the same as SET hits and cross check how efficiency changes...
